version: '3'

services:
  bionexo-rpa-app:
    build:
      context: .
      dockerfile: ___docker/Dockerfile
    container_name: bionexo-rpa-app
    restart: unless-stopped
    volumes:
      - .:/var/www
    depends_on:
      - bionexo-rpa-db
      - bionexo-rpa-web
    networks:
      - bionexo-rpa-network

  bionexo-rpa-web:
    image: nginx:latest
    container_name: bionexo-rpa-web
    restart: unless-stopped
    ports:
      - "8000:80"
    volumes:
      - .:/var/www
      - ./___docker/nginx/:/etc/nginx/conf.d/
    networks:
      - bionexo-rpa-network

  bionexo-rpa-db:
    image: mysql:5.7
    container_name: bionexo-rpa-db
    restart: unless-stopped
    volumes:
        - ./___docker/mysql:/var/lib/mysql
    ports:
      - "3307:3306"
    environment:
        MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
        MYSQL_DATABASE: ${DB_DATABASE}
        MYSQL_USER: ${DB_USERNAME}
        MYSQL_PASSWORD: ${DB_PASSWORD}
    networks:
      - bionexo-rpa-network

  bionexo-rpa-selenium:
    image: selenium/standalone-chrome
    container_name: bionexo-rpa-selenium
    ports:
      - "4444:4444"
    networks:
      - bionexo-rpa-network

networks:
  bionexo-rpa-network:
    driver: bridge
